name: echomirror_server
description: EchoMirror Serverpod server
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  serverpod: ^3.0.1
  serverpod_auth_idp: ^3.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  serverpod_test: ^3.0.1
